design
niyazm524/AndroidSummer2020 pull request #40
Opened 2020-07-12 17:06 UTC by ddddi21

…fix design(im dead) (mb will be update) + fix tabl with questions(cell size and etc(mb wrong, но у меня все красивенько))

2020-07-12 18:04 UTC, niyazm524 requested changes
Проект не билдится
![image](https://user-images.githubusercontent.com/32315145/87253357-2d6b7b80-c483-11ea-9f60-4ed755ee3338.png)


__________________________
+ может без кастомных шрифтов? или прям обязательно

2020-07-12 18:26 UTC, ddddi21 commented
а че почему так. ты со всеми ресурсами смотришь?
![image](https://user-images.githubusercontent.com/55531213/87253766-580b0380-c486-11ea-9ee1-c3ae67aab234.png)

2020-07-12 18:40 UTC, ddddi21 commented
так, файлы оказывается эти не загрузились. щас разберусь

2020-07-12 18:52 UTC, ddddi21 commented
так все, я вроде два файла вручную загрузила. должно все работать. я не поняла почему они вместе со всеми не загрузились во время пуша(я вроде все отмечала)

2020-07-13 09:43 UTC, niyazm524 approved these changes
Окей, теперь проект собирается
Выглядит конечно очень экспериментально, смело, я бы даже сказал
Короче не знаю мерджить или еще подумать, наверное если чё потом еще отшлифуем. Я апрув сделаю, ты сама реши, когда мержить

2020-07-13 09:51 UTC, ddddi21 commented
не нравится дизайн или что? он конечно не окончательный, но +- готов. или ты имеешь в виду что он не в синих тонах как СИ? А зачем нам делать как в СИ?

2020-07-13 10:11 UTC, ddddi21 commented
или ты про таблицу и цены? просто щас мы выяснили что там поехали цифры но это ж поправимо (на момент моего дезигна там было две категории и было норм все)
![Pa5FiQciFeA](https://user-images.githubusercontent.com/55531213/87292974-4bc88a00-c50a-11ea-98f4-f8a491760c4d.jpg)

2020-07-13 10:41 UTC, merged