Feature siq parse
niyazm524/AndroidSummer2020 pull request #43
Opened 2020-07-13 08:18 UTC by GalievBulat

2020-07-13 09:33 UTC, niyazm524 requested changes
Всё отлично, как добавишь трай кетч сразу смержу

2020-07-13 09:33 UTC, niyazm524 commented on app/src/main/java/ru/itis/androidsummer/GameInterfaceActivity.kt
> +    }
хорошо бы сюда try-catch навесить, потому что из тех функций я их убрал..

2020-07-13 10:38 UTC, GalievBulat commented on app/src/main/java/ru/itis/androidsummer/GameInterfaceActivity.kt
> +    }
если туда блок try/cath вешать, то activity дальше работает и выдает уже ошибку об отсутствии адаптера поэтому я блок в основную часть вынес

2020-07-14 07:38 UTC, niyazm524 approved these changes

2020-07-14 07:38 UTC, merged