complete ui
niyazm524/AndroidSummer2020 pull request #51
Opened 2020-07-14 16:59 UTC by ddddi21

профиль, сеттинг + по мелочам 
фикс ussue
пс.(мб будет апдейт)
пс2(определенно будет апдейт после появления сетей и рейтинга)

2020-07-14 18:07 UTC, niyazm524 requested changes
КРАСИВО
Подправь строчку и мержим

2020-07-14 18:07 UTC, niyazm524 commented on app/src/main/java/ru/itis/androidsummer/HelpActivity.kt
> +        }
тут надо просто finish() вызывать, иначе в стеке активити остается хелп

2020-07-14 18:21 UTC, ddddi21 commented on app/src/main/java/ru/itis/androidsummer/HelpActivity.kt
> +        }
аа, везде, где возврат к меню так делать?

2020-07-14 18:22 UTC, ddddi21 commented on app/src/main/java/ru/itis/androidsummer/HelpActivity.kt
> +        }
спасибо :3

2020-07-14 18:27 UTC, ddddi21 commented
готово

2020-07-15 11:45 UTC, niyazm524 approved these changes
найсс

2020-07-15 11:46 UTC, merged