Feature/siq file setting
niyazm524/AndroidSummer2020 pull request #56
Opened 2020-07-15 07:59 UTC by GalievBulat

2020-07-15 12:14 UTC, niyazm524 commented
// REF: Issue #4 
@GalievBulat Посмотри как принято называть id элементов в layout

2020-07-15 12:17 UTC, niyazm524 requested changes
@GalievBulat 
@ddddi21 
Что-то вы не совместили свои идеи насчет UX приложения в какую-то общую идею, вам нужно вместе сесть и решить как всё должно работать (где настройки, что там есть, когда выбор пака)
P.S. свои идеи я описал в файле `MainMenuActivity.kt`, [загляните](https://github.com/niyazm524/AndroidSummer2020/blob/2c40c85977d0e08a5aef5d500eaf334c017c3aaa/app/src/main/java/ru/itis/androidsummer/MainMenuActivity.kt)

2020-07-15 12:28 UTC, niyazm524 commented
## + тащить в APK **50 МБ** не очень много желания если честно, подгрузку с файловой системы бы (на крайняк можно и так оставить, но не оч красиво)

2020-07-15 13:10 UTC, ddddi21 commented on app/src/main/java/ru/itis/androidsummer/MainMenuActivity.kt
> +            Bulat version: startActivity(Intent(this, PackChoosing::class.java))
![W8GXw05I7WI](https://user-images.githubusercontent.com/55531213/87548552-55422580-c6b5-11ea-95e2-417a22131540.jpg)

2020-07-15 23:01 UTC, ddddi21 commented
Нияз, тебя тоже ставлю в известность об этой находке
![ARGYrpShqSU](https://user-images.githubusercontent.com/55531213/87608317-420c7580-c708-11ea-9aed-008ed74b0d6a.jpg)

2020-07-15 23:08 UTC, ddddi21 commented
> Нияз, тебя тоже ставлю в известность об этой находке
> ![ARGYrpShqSU](https://user-images.githubusercontent.com/55531213/87608317-420c7580-c708-11ea-9aed-008ed74b0d6a.jpg)
кароче там посмотрите, я думаю не нужно для выбора паков отдельное активити, просто перенести весь код в рекуклер в созданный активити из моей ветки

2020-07-16 09:50 UTC, niyazm524 requested changes
ну всё, осталось только смержить ваши функциональности в одну конфетку

2020-07-16 09:50 UTC, niyazm524 commented
Я смержил с мастера изменения, так что теперь тут всё самое последнее

2020-07-17 07:42 UTC, niyazm524 approved these changes
Немного переделал способ передачи информации о выбранном паке: [коммит](https://github.com/niyazm524/AndroidSummer2020/pull/56/commits/f47f2e320002a81982cca7f36056ffaa7fc1beba) 
В остальном всё супер

2020-07-17 07:42 UTC, merged